Repository icaros-usc/pyribs, pull requests merged in 2022-06, with the labels that each got.

#204 in-comment type hint rich linking and parameter defaults
  HISTORY.md
  docs/conf.py
  setup.py
Labels: documentation

#203 fix typo and formatting in `ribs/visualize.py`
  HISTORY.md
  ribs/visualize.py
Labels: documentation

#213 Replace elite_with_behavior with batched elites_with_measures method in archives
  HISTORY.md
  ribs/archives/_archive_base.py
  tests/archives/archive_base_test.py
Labels: API

#212 Allow unlimited max args in pylint
  .pylintrc
Labels: infrastructure

#214 Add index_of_single method for getting index of measures for one solution
  HISTORY.md
  ribs/archives/_archive_base.py
  tests/archives/archive_base_test.py
Labels: API
